# https://taskfile.dev/

version: '3'

vars:
  BUILD_DIR: build

tasks:
  run:
    desc: "Run an example (ex: task run EXAMPLE=sender)"
    requires:
      vars: [EXAMPLE]
    cmd: go run examples/{{ .EXAMPLE }}/{{ .EXAMPLE }}.go

  test:
    desc: "Run tests"
    vars:
      TOOLS_ARGS: '{{ .TOOLS_ARGS }}'
      TEST_ARGS: '{{ .TEST_ARGS | default .CLI_ARGS }}'
    cmd: go run gotest.tools/gotestsum@latest --format testname {{ .TOOLS_ARGS }} -- ./... -race -count=1 {{ .TEST_ARGS }}

  coverage:
    desc: "Run and open test coverage"
    vars:
      MODE: '{{.MODE | default "html"}}'
      FILE: '{{ .BUILD_DIR }}/coverage.out'
    cmds:
      - task: test
        vars: 
          TEST_ARGS: -coverprofile={{ .FILE }}
      - grep -v '/examples/' {{ .FILE }} > {{ .FILE }}.filtered # Remove examples from test
      - go tool cover -{{ .MODE }}={{ .FILE }}.filtered
    preconditions:
      - mkdir -p {{ .BUILD_DIR }}

  check:
    desc: "Clean, tidy and audit"
    cmds:
      - task: fmt
      - task: vet
      - task: tidy
      - go run golang.org/x/vuln/cmd/govulncheck@latest -show verbose ./...

  fmt:
    desc: "Run formatting"
    cmd: go fmt ./...

  vet:
    desc: "Run linting"
    cmd: go vet ./...

  tidy:
    desc: "Clean and tidy dependencies"
    cmd: go mod tidy -v

  docs:
    desc: "Open local docs website"
    cmd: go run golang.org/x/pkgsite/cmd/pkgsite@latest -open

  update:
    desc: "Update dependencies"
    cmds:
      - task: tidy
      - go get -u ./...